### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by evelikov**
Hi all,

As a lazy Archer I've just updated my system only to find some odd changes to the PKGBUILDs. This series reverts some of the behaviour which I believe is the correct one, plus syncs up the mingw-w64 PKGBUILD.

Feel free to pull, if it's looking good :-)

### CODE REVIEW

**Comment by bwidawsk** [comment]
I am not an expert, but I think commit #1 is wrong. You are supposed to be using conflicts() and provides () instead of replaces(). AIUI replaces() is designed for replacing obsoleted packages, which we are not doing here.

Patch #2 looks good

Patch #3: looks good

Patch #4: I thought optdepends() has no real meaning. Can you explain what you're trying to achieve with the patch?

Patch #5: I have no intention to look at the mingw patches, but I'll assume it's a warranted update.

**Comment by evelikov** [comment]
Wrt #1 you're absolutely correct - I've mixed up replaces() with provides(). The latter should be used in here.

About the optdepends() - it serves as a guide. For example program A was built with backends for X and Y, yet one can choose from either one at run-time. As such both X and Y are mentioned in the list, with a brief description. Without the optdepends list, one does has limited idea why loading/using the backend fails.

Note: a while back Arch decided to merge all the libs (libegl, libgbm..) into a single package, but one never knows when they'll decide to split them again.

**Comment by bwidawsk** [comment]
Can resubmit the pull request patch1? I don't know how to easily do a pull and drop a patch. I'll update the AUR packages afterwards.

**Comment by evelikov** [comment]
Sure. It's coming in a second.

**Pull request closed without merging**
